name: flutter_etrucknet_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_bloc: ^8.0.0
  provider: ^6.0.0
  google_maps_flutter: ^2.2.1
  latlong2: ^0.8.0
  geocoding: ^3.0.0
  country_picker: ^2.0.2

  cupertino_icons: ^1.0.8
  flutter_map: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
